"""empty message

Revision ID: 0daabda5e421
Revises: 
Create Date: 2020-11-24 23:11:59.087522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0daabda5e421'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket',
    sa.Column('t_id', sa.Integer(), nullable=False),
    sa.Column('t_title', sa.String(length=20), nullable=True),
    sa.Column('t_desc', sa.String(length=100), nullable=True),
    sa.Column('emp_id', sa.Integer(), nullable=True),
    sa.Column('t_submitter', sa.String(), nullable=True),
    sa.Column('p_id', sa.Integer(), nullable=True),
    sa.Column('t_priority', sa.String(), nullable=True),
    sa.Column('t_status', sa.String(), nullable=True),
    sa.Column('t_type', sa.String(), nullable=True),
    sa.Column('t_create_date', sa.String(), nullable=True),
    sa.Column('t_close_date', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('t_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket')
    # ### end Alembic commands ###
