"""empty message

Revision ID: 603687dcc419
Revises: 0daabda5e421
Create Date: 2020-11-25 21:35:27.760163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '603687dcc419'
down_revision = '0daabda5e421'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('submitter_id', sa.Integer(), nullable=True))
    op.drop_column('ticket', 't_submitter')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('t_submitter', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('ticket', 'submitter_id')
    # ### end Alembic commands ###
