"""empty message

Revision ID: e1d6791d222b
Revises: 603687dcc419
Create Date: 2020-11-28 23:35:11.796031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1d6791d222b'
down_revision = '603687dcc419'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('submitter_email', sa.String(), nullable=True))
    op.drop_column('ticket', 'submitter_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('submitter_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('ticket', 'submitter_email')
    # ### end Alembic commands ###
